### ISSUE TITLE
[BUG] - Broken missing values plot for small percentage of missing values

### ISSUE THREAD

**Issue by Abermal** [akanz1/klib#14]
**Describe the bug**
The missing value plot gets broken for a small missing values percentage.

**To Reproduce**
```python
df = pd.DataFrame.from_dict({'col': np.ones(1000)})
df.loc[:2] = np.NaN
klib.missingval_plot(df)
```

**Expected behavior**
Appropriate positioning of the text, y axes labels

**Screenshots**
![image](https://user-images.githubusercontent.com/34352604/146552452-88bfbdfe-a351-4f4a-a5bd-c34e1b8d05ed.png)

I have a fix, but I'm not allowed to push my branch. How can I do it?

P.S. awesome library, thanks for the work!

**Comment by akanz1** [comment]
Hi @Abermal thanks a lot, feel free to create a Pull Request and i'll take a look later today! :)

**Comment by akanz1** [comment]
@Abermal just took a quick look, all it takes is an update to the number of decimals on the y-axis, will fix and release :)

**Comment by Abermal** [comment]
Thanks!

There is another line(694) to fix:
```python    
    for rect, label in zip(ax1.patches, mv_cols):
        height = rect.get_height()
        ax1.text(
            0.1 + rect.get_x() + rect.get_width() / 2,
            height + 0.5,  # The problem is here, you could replace it with  "height * 1.05"
            label,
            ha="center",
            va="bottom",
            rotation="90",
            alpha=0.5,
            fontsize="11",
        )
```
