### ISSUE TITLE
drop preprocessing module and sklearn dependency

### ISSUE THREAD

**Issue by akanz1** [akanz1/klib#20]
drop pipeline related features / module and reduce number of dependencies

**Comment by batmanscode** [comment]
This would be great. Had a working project that's now having scikit-learn version issues

**Comment by akanz1** [comment]
@batmanscode v1.0.1 has just been released, which no longer requires scikit-learn
 https://github.com/akanz1/klib/releases/tag/v1.0.1

**Comment by batmanscode** [comment]
@akanz1 brilliant, thank you! 😃
