### ISSUE TITLE
[BUG] - ... The command -- klib.dist_plot(df) does not plot the distribution for all the numeric features of a Dataframa

### ISSUE THREAD

**Issue by Amit-0905** [akanz1/klib#241]
**Describe the bug**
The issue is that the the command -- klib.dist_plot(df) does not plot the distribution for all the numeric features of a Dataframa it just plots the ditribution for the first numeric feature only.
**To Reproduce**
1. Go to python notebook and import klib
2. Create a dataframe from any dataset in my case i used "df = pd.read_csv('https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv')"
3. then use - klib.dist_plot(df) to plot the distribution
4. See error that it plots for the first numeric only in case use also set the showall to True

**Screenshots**
![image](https://github.com/user-attachments/assets/a987883e-1f3c-4a79-93dd-06b394d58304)

**Comment by akanz1** [comment]
Thank you for reporting this @Amit-0905 . It's been fixed in klib 1.2.0
