### ISSUE TITLE
[BUG] - data cleaning sometimes returns float32 instead of float64

### ISSUE THREAD

**Issue by alessandrofilisetti** [akanz1/klib#29]
**Describe the bug**
Hi @akanz1, first of all thanks for this amazing package. I do not know whether this is properly a bug. 
The cleaning function sometimes converts data to float32 instead of float64, and the dist_plot function returns a `ValueError: data type <class 'numpy.object_'> not inexact `. If I manually convert the data with `.astype(float)`everything works fine. 

Here is the data that produces the error, you can create a data frame col with that data and try out

[0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 2.0331595,
 1.0165797,
 2.0331595,
 2.0331595,
 0.0,
 2.0331595,
 1.0165797,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 2.0331595,
 1.0165797,
 2.0331595,
 2.0331595,
 0.0,
 2.0331595,
 1.0165797,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 2.0331595,
 1.0165797,
 2.0331595,
 2.0331595,
 0.0,
 2.0331595,
 1.0165797,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 2.0331595,
 1.0165797,
 2.0331595,
 2.0331595,
 0.0,
 2.0331595,
 1.0165797,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 0.0,
 0.0,
 2.0331595,
 2.0331595,
 2.0331595,
 1.0165797,
 2.0331595,
 2.0331595,
 0.0,
 2.0331595,
 1.0165797]

**Comment by akanz1** [comment]
@alessandrofilisetti Thank you for reporting this, i will take a look later this week as soon as i am free :)

**Comment by akanz1** [comment]
@alessandrofilisetti i've released 1.0.2 which should fix this issue
