### ISSUE TITLE
[BUG] - Cannot set non-string value {value} into a StringArray with klib.cat_plot

### ISSUE THREAD

**Issue by AndreaMorichetta** [akanz1/klib#3]
Once running `klib.cat_plot(df_cleaned)` I get this error:
`Cannot set non-string value '2' into a StringArray.`

<img width="834" alt="Screen Shot 2020-10-05 at 11 01 32 AM" src="https://user-images.githubusercontent.com/18530257/95060155-2ce92680-06fa-11eb-9532-38c051e3bcc0.png">

Python version: Python 3.6.9
Pandas version: 1.1.2

My data look like this:
0   vmid               string  
 1   subscriptionid     category
 2   deploymentid       category
 3   vmcreated          int32   
 4   vmdeleted          int32   
 5   maxcpu             float32 
 6   avgcpu             float32 
 7   p95maxcpu          float32 
 8   vmcategory         category
 9   vmcorecountbucket  category
 10  vmmemorybucket     category
 11  lifetime_h         float32

**Comment by akanz1** [comment]
@AndreaMorichetta can you make sure that you have the latest version (0.1.1)? I ran into this error myself a couple of weeks ago and judging by the traceback it seems like you're on an older version.

Let me know if that fixes it! :)

**Comment by AndreaMorichetta** [comment]
@akanz1 thank you! The problem was with my Python version, which was 3.6.9. I updated it and reinstalled klib; now it works fine!
