### ISSUE TITLE
[BUG] - cat_plot cmap not supported

### ISSUE THREAD

**Issue by Zalfrin** [akanz1/klib#7]
Documentation says cat_plot accepts cmap as an optional parameter, but the function doesn't actually include this.

**Comment by akanz1** [comment]
Hi @Zalfrin, Thank you for filing this issue, that's a good find!

The cmap parameter is indeed not used anymore and instead has been replaced with two color inputs to build a diverging cmap. Please note that the docs are a bit outdated, but rebuilding them is on my to-do list.
